apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  name: service-simple-service
spec:
  selector:
    app: jenkins-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000  # You can specify your desired NodePort value here
  type: NodePort
=======
  name: frontend-service
spec:
  selector:
    app: nginx-jenkins
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
      nodePort: 30008
  type: NodePort
    dev
